version: 2
jobs:
  install-dep:
    docker:
      - image: circleci/node:12.19.0

    working_directory: ~/happy/web
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build:
    docker:
      - image: circleci/node:12.19.0

    working_directory: ~/happy/web

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn run build
