version: 2.17
jobs:
  build:
    docker:
      - image: circleci/node:12.19.0
    working_directory: ~/happy/web
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm
          command: npm install
          paths:
            - ./node_modules
      - run:
          name: build-project
          command: npm run build       