version: 2.17
jobs:
  build:
    docker:
      - image: circleci/node:12.19
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          working_directory: ~/web
          name: install-dependencies
          command: npm install
          cache-path: node_modules
      - run:
          name: build-project
          command: npm run build
          paths:
            - ~/web
