version: 2.1

jobs:
  cloud-functions:
    docker:
      - image: circleci/node:12.19.0

    working_directory: ~/happy/web

    steps:
      - checkout
      - run: npm install
   
  web:
    docker:
      - image: circleci/node:12.19.0

    working_directory: ~/happy/web
      - checkout
      - run: cd web && npm install
      - run: cd web && npm run lint
      - run: cd web && npm run build

workflows:
  version: 2
  concurrently:
    jobs:
      - cloud-functions
      - web
