version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.19

    working_directory: ~/happy/web

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "web/package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "web/package.json" }}
        
      - build:
      - run: npm run build
