version: 2
jobs:
  install-dep:
    docker:
      - image: circleci/node:12.19.0

    working_directory: ~/happy/web
    steps:
      - checkout

      - run: yarn install

      - save_cache:
          paths:
            - node_modules

  build:
    docker:
      - image: circleci/node:12.19.0

    working_directory: ~/happy/web

    steps:
      - checkout
      
      - run: yarn run build
