version: 2.1

jobs:
  build-project:
    docker:
      - image: circleci/node:12.19.0
    working_directory: ~/happy
    steps:
      - checkout
      - run: cd web && npm install
      - run: cd web && npm run build
      
workflows:
  version: 2.1
  workflow:
    jobs:
    - build-project
